"""Add performance indices

Revision ID: 467051f351f0
Revises: b90ff9fefd2a
Create Date: 2026-03-13 20:22:36.371890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467051f351f0'
down_revision = 'b90ff9fefd2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_types', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('activity_types_name_key'), type_='unique')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('student_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_activities_campus_type'), ['campus_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_activities_created_at'), ['created_at'], unique=False)
        batch_op.drop_constraint(batch_op.f('student_activities_student_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['student_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_department'), ['department'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_department'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    with op.batch_alter_table('student_activities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('student_activities_student_id_fkey'), 'users', ['student_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_student_activities_created_at'))
        batch_op.drop_index(batch_op.f('ix_student_activities_campus_type'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    with op.batch_alter_table('activity_types', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('activity_types_name_key'), ['name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
