"""add weightage

Revision ID: b90ff9fefd2a
Revises: c3a1f5e8d201
Create Date: 2026-03-04 20:30:20.433875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b90ff9fefd2a'
down_revision = 'c3a1f5e8d201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weightage', sa.Integer(), nullable=False, server_default='10'))

    with op.batch_alter_table('student_activities', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_sa_att_uploader', 'users', ['attendance_uploaded_by'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_activities', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sa_att_uploader', type_='foreignkey')

    with op.batch_alter_table('activity_types', schema=None) as batch_op:
        batch_op.drop_column('weightage')

    # ### end Alembic commands ###
