"""Add soft delete and notifications

Revision ID: be7e1e983d10
Revises: 2bd3043d53d6
Create Date: 2026-02-14 20:26:10.554399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7e1e983d10'
down_revision = '2bd3043d53d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('student_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deletion_reason', sa.Text(), nullable=True))
        batch_op.drop_constraint(batch_op.f('student_activities_verification_token_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_student_activities_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_activities_verification_token'), ['verification_token'], unique=True)
        batch_op.drop_constraint(batch_op.f('student_activities_activity_type_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'activity_types', ['activity_type_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deletion_reason', sa.Text(), nullable=True))
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_institution_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_institution_id'), ['institution_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_institution_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_institution_id_key'), ['institution_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('deletion_reason')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('student_activities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('student_activities_activity_type_id_fkey'), 'activity_types', ['activity_type_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_student_activities_verification_token'))
        batch_op.drop_index(batch_op.f('ix_student_activities_is_deleted'))
        batch_op.create_unique_constraint(batch_op.f('student_activities_verification_token_key'), ['verification_token'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('deletion_reason')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    # ### end Alembic commands ###
